export const ADMIN_ROUTE = '/admin'
export const MENU_ROUTE = '/'
export const BASKET_ROUTE = '/basket'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const DISH_ROUTE = '/dish'
export const PROFILE_ROUTE = '/profile'